"""Venue model

Revision ID: 83251b1deb50
Revises: 8b21528db044
Create Date: 2020-10-09 16:02:37.668172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83251b1deb50'
down_revision = '8b21528db044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('artist_name', sa.String(length=120), nullable=True),
    sa.Column('venue_name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Venue', sa.Column('past_shows', sa.Integer(), nullable=False))
    op.add_column('Venue', sa.Column('past_shows_count', sa.Integer(), nullable=True))
    op.add_column('Venue', sa.Column('upcoming_shows', sa.Integer(), nullable=False))
    op.add_column('Venue', sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Venue', 'Show', ['upcoming_shows'], ['id'])
    op.create_foreign_key(None, 'Venue', 'Show', ['past_shows'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'upcoming_shows_count')
    op.drop_column('Venue', 'upcoming_shows')
    op.drop_column('Venue', 'past_shows_count')
    op.drop_column('Venue', 'past_shows')
    op.drop_table('Show')
    # ### end Alembic commands ###
