"""empty message

Revision ID: d709aba4f6d8
Revises: 891afe4656d5
Create Date: 2020-10-18 20:14:28.449966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd709aba4f6d8'
down_revision = '891afe4656d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
